[pytest]
# Dossier par défaut où chercher les tests
testpaths = tests

# Enregistrement de nos marqueurs personnalisés pour éviter les warnings
markers =
    integration: Marque un test comme test d'intégration (nécessite une vraie base de données allumée)
    unit: Marque un test comme unitaire (rapide, sans dépendance externe)